#!/bin/sh

aur_helper=yay

if [ -z "$(pacman -Qu)" ]
then
	debug-message 'INFO' 'Packages up to date!'
	read -r _
	exit
fi

debug-message 'INFO' 'Beginning upgrading packages'
debug-message 'WARNING' 'sudo pacman -Syy'
if [ -n "$(pacman -Qu linux)" ]
then
	debug-message 'INFO' 'Available Linux Kernel update'
	debug-message 'WARNING' '60 seconds until reboot after sucessful upgrade'
	pacman -Qu linux
	sudo pacman -Syu
	notify-send --urgency=critical 'Reboot' '1 minute until reboot'
	sleep 60
	notify-send "Rebooting Machine..."
	sleep 1
	reboot
else
	sudo pacman -Syu
fi

printf 'Upgrade AUR Packages? [y/N] '
read -r aur
if [ "$aur" = "y" ] || [ "$aur" = "Y" ] || [ "$aur" = "yes" ]
then
	$aur_helper --aur -Syyu
fi

debug-message 'OK' 'Upgrade Complete'
printf 'Press <Enter> to exit window.\n'
read -r _

pkill -RTMIN+2 dwmblocks
