#!/bin/sh

# Dependencies:
# brightnessctl
# libnotify

get_brightness() {
	brightnessctl | awk '/Current brightness/ {print $4}' | sed 's/[()%]//g'
	return
}

set_brightness() {
	case $2 in
		+) brightnessctl set "+$1%" ;;
		-) brightnessctl set "$1%-" --min-value 1 ;;
	esac
}

set_brightness "$1" "$2"

appName='change-brightness'
msgTag='brightness'
brightness="$(get_brightness)"
brightness_level="$(echo "$brightness" | awk '{ print sprintf("%.0f", $1/100*4) }')"
case "$brightness_level" in
	0) icon='brightness-low' ;;
	1) icon='brightness-medium' ;;
	2) icon='brightness-medium' ;;
	3) icon='brightness-high' ;;
	4) icon='brightness-high' ;;
esac
notify-send --app-name="$appName" \
	--urgency=low \
	--icon="$icon" \
	--hint=string:x-dunst-stack-tag:"$msgTag" \
	--hint=int:value:"$brightness" "Brightness: ${brightness}%"
