#!/usr/bin/env sh

counter=20

[ ! "$1" = "" ] && counter=$1

while [ "$counter" -gt 0 ]
do
	figlet "$counter" | lolcat &
	counter=$((counter - 1))
	sleep 1
done

notify-send --urgency=critical "Time is up"
