#!/bin/sh

# TODO: add usage/help page

[ -t 1 ] \
	&& [ -x "$(command -v tput)" ] \
	&& [ -n "$(tput colors)" ] \
	&& [ "$(tput colors)" -ge 8 ] \
	&& color_support=true || color_support=false

if $color_support
then
	color=36
	case $1 in
		INFO)    color=36 ;;
		ERROR)   color=31 ;;
		WARNING) color=33 ;;
		OK)      color=32 ;;
	esac
	printf '\033['"$color"'m[%s]:\033[0m %s\n' "$1" "$2"
else
	printf '[%s]: %s\n' "$1" "$2"
fi
