#!/bin/sh
set -e

usage () {
	echo "Usage: $(basename "$0") <archive file> [output directory]"
	echo "output directory is optional"
	echo "if output directory is not provided, it will extract here"
	exit 1
}

[ $# -eq 0 ] || [ $# -gt 2 ] && usage

TEMP=$(getopt \
	--options 'hnq' \
	--long 'help,no-notification,quiet' \
	--name "$(basename "$0")" -- "$@")

if [ $? -ne 0 ]; then
	echo 'Terminating...' >&2
	exit 1
fi

# Note the quotes around "$TEMP": they are essential!
eval set -- "$TEMP"
unset TEMP

while true
do
	case "$1" in
		-h | --help)
			usage
			;;
		--)
			shift
			break
			;;
		*) # Option not dealt with
			echo 'Internal error!' >&2
			exit 1
			;;
	esac
done

if [ ! -f "$1" ]
then
	echo "'$1' is not a valid file"
	exit 1
fi

(
archive="$(realpath "$1")"
mime="$(file --brief --mime-type "$archive")"
if [ -n "$2" ]
then
	if [ ! -d "$2" ]
	then
		mkdir -p "$2"
	fi
	cd "$2" >/dev/null
fi
case "$mime" in
	application/gzip)            gunzip "$archive" ;;
	application/x-7z-compressed) 7z x "$archive"   ;;
	application/x-rar)           unrar x "$archive"  ;;
	application/x-tar)           tar xf "$archive" ;;
	application/zip)             unzip "$archive"  ;;
	# *.bz2)       bunzip2 "$1"     ;;
	# *.tar.bz2)   tar xjf "$1"     ;;
	# *.tar.gz)    tar xzf "$1"     ;;
	# *.tbz2)      tar xjf "$1"     ;;
	# *.tgz)       tar xzf "$1"     ;;
	# *.Z)         uncompress "$1"  ;;
	*)             printf "'%s': %s cannot be extracted via %s\n" \
		"$1" \
		"$mime" \
		"$(basename "$0")"
			exit 1 ;;
esac
)
