#!/bin/sh

if [ "$(pgrep "$(basename "$0")" | wc --lines)" -gt 2 ]
then
	printf 'Instance of %s already running\n' "$(basename "$0")"
	exit 1
fi

while true
do
	if [ "$(pgrep "^mpd$")" = "" ]
	then
		printf 'No instance of %s running\n' 'mpd'
		exit 1
	fi
	mpc current --wait
	rm /tmp/cover.png
	ffmpeg \
		-loglevel quiet \
		-y \
		-i "$(xdg-user-dir MUSIC)/$(mpc --format %file% current)" \
		-an -vcodec copy /tmp/cover.png
	notify-music
	pkill -RTMIN+20 dwmblocks
done
