#!/bin/sh

fzf_menu() {
	echo "$(mpc playlist | fzf --reverse)"
}

wofi_menu() {
	echo "$(mpc playlist | wofi --show dmenu --prompt='Select a song: ')"
}

dmenu_menu() {
	echo "$(mpc playlist | dmenu -p 'Select a song:')"
}

case "$1" in
	fzf) selected_song="$(fzf_menu)";;
	wofi) selected_song="$(wofi_menu)";;
	dmenu) selected_song="$(dmenu_menu)";;
	*)
		tty --silent && selected_song="$(fzf_menu)" ||
		case $XDG_SESSION_TYPE in
		x11) selected_song="$(dmenu_menu)";;
		wayland) selected_song="$(wofi_menu)";;
	esac;;
esac

[ "$selected_song" = "" ] && exit 0

# Get the index of the selected song
index=$(echo "$(mpc playlist)" | grep -n "$selected_song" | cut -d ':' -f1)

# Play the selected song using mpc
mpc play "$index"
