#!/bin/sh

progress="$(mpc status | awk 'NR==2 { gsub(/[(%)]/,""); print $4 }')"
message="$(mpc status \
	| sed 's/playing/  /;s/paused/  /;3s/: off/: /g;3s/: on/: /g;3s/ \{2,\}/\n/g')

$(mpc stats)"

notify-send \
	--app-name=music \
	--urgency=low \
	--icon="/tmp/cover.png" \
	--hint="int:value:$progress" "MPD" "$message"
