#!/bin/sh

[ -n "$1" ] && BLOCK_BUTTON=$1

case "$BLOCK_BUTTON" in 
	1) notify-send "$(nmcli)";;
	2) notify-send "Status Bar Module: internet " "\- X: wifi disabled
\: no wifi connection
\: wifi connection with quality
\: no ethernet
\: airplane mode
\: ethernet working
\: vpn is active
\<b>Left Click</b>, shows Network Manager statistics.
\<b>Middle Click</b>, shows this help notification.
\<b>Shift + Left Click</b>, opens nmtui.
\<b>Ctrl + Right Click</b> to edit this module." ;;
	4) scratchpad --wait --title "Network" --command "nmtui" ;;
	9) scratchpad \
		--title "Edit $(basename "$0")" \
		--working-directory "$(dirname "$0")" \
		--command "$EDITOR $0" ;;
esac

interface="$(ip address | awk '/state UP/ {print $2}' | sed s/://)"
ipaddress="$(ip address | grep "$interface" | awk '/inet/ {print "" $2}' | \
	sed 's/\/[[:digit:]]\+//')"
if grep -xq 'up' /sys/class/net/w*/operstate 2>/dev/null ; then
	interface="$(ip address | awk '/state UP/ {print $2}' | sed s/://)"
	wifiicon="$(awk '/^\s*w/ { print "", int($3 * 100 / 70) "%" }' \
		/proc/net/wireless)"" $ipaddress"
elif grep -xq 'down' /sys/class/net/w*/operstate 2>/dev/null ; then
	grep -xq '0x1003' /sys/class/net/w*/flags && wifiicon="" || wifiicon="X"
  # else
	# [ "$(cat /sys/class/rfkill/rfkill1/soft 2>/dev/null)" = "1" ] && wifiicon=""
fi
printf "[%s%s%s]\n" \
	"$wifiicon" \
	"$(sed "s/down//;s/up/ $ipaddress/" /sys/class/net/e*/operstate 2>/dev/null)" \
	"$(sed "s/.*//" /sys/class/net/tun*/operstate 2>/dev/null)"

unset interface
unset ipaddress
unset wifiicon
