#!/bin/sh

folder="$HOME/Imagens/Screenshots/"
cd "$folder" || exit 1

file="$HOME/Imagens/Screenshots/Capture-$(date +%Y-%m-%d_%H-%m-%s).png"
quality=100

if [ "$XDG_SESSION_TYPE" = "x11" ]
then
	case $1 in
		fullscreen )
			scrot --quality $quality --file "$file";;
		select )
			scrot --quality $quality --select=capture --file "$file";;
		current )
			scrot --quality $quality --focused --file "$file";;
		* )
			scrot --quality $quality --file "$file";;
	esac

	[ -f "$file" ] || exit 0

	notify-send \
		--icon "$file" \
		"Screenshot Taken Successfully" \
		"Copied to Clipboard  "
elif [ "$XDG_SESSION_TYPE" = "wayland" ]
then
	case $1 in
		fullscreen )
			grim "$file";;
		select )
			grim -g "$(slurp)" "$file";;

		# TODO: Implent Current window selected in wayland
		#
		# current )
		# 	grim -q $quality "$file";;
		* )
			grim "$file";;
	esac

	[ -f "$file" ] || exit 0

	wl-copy < "$file"
	notify-send \
		--icon "$file" \
		"Screenshot Taken Successfully" \
		"Copied to Clipboard  "
fi
