#!/usr/bin/env python3

from sys import argv
from time import sleep

if __name__ != '__main__' or len(argv) < 3:
    print(f'''Usage
{argv[0]} "Text" <width>
{argv[0]} "Text" <width> --time=.1 --iterations=3''')
    exit(0)

width: int = int(argv[2])
text: str = ' ' * width + argv[1][:]
time_seconds: float = .15
iterations: int | float = float('inf')

for argument in argv[3:]:
    if argument.startswith('--time'):
        time_seconds = float(argument.split('=')[1])
    elif argument.startswith('--iterations'):
        iterations = int(argument.split('=')[1])

while iterations > 0:
    for _ in range(len(text)):
        print(text[:width], end = '\r')
        text = text[1:] + text[:1]
        sleep(time_seconds)
    iterations -= 1
