#!/bin/sh

prompt="Emoji: "
case $XDG_SESSION_TYPE in
	x11)
		selection="dmenu -p "
		clipboard="xclip -selection clipboard"
		;;
	wayland)
		selection="wofi --insensitive --show dmenu --prompt "
		clipboard="wl-copy"
		;;
esac

[ "$(tty)" = "/dev/pts/0" ] && selection="fzf --prompt "


emoji="$(cat "$HOME/.local/share/emojis.txt" | $selection "$prompt" | awk '{print $1}')"
[ "$emoji" = "" ] && exit

printf "$emoji" | $clipboard
notify-send "$emoji copied to clipboard"
