#!/bin/sh

# Dependencies:
# - feh
# - swww

DIR="$HOME/Imagens/Wallpapers"
WALLPAPER="/tmp/wallpaper.txt"
SLEEPTIME=600
PID=""

change_wallpaper() {
	find "$DIR" \
		-maxdepth 1 \
		-type f \
		-name "*.jpg" -o \
		-name "*.png" -o \
		-name "*.gif" \
		| shuf --head-count=1 > "$WALLPAPER"
}

update_wallpaper() {
	wallpaper_file="$(head -1 "$WALLPAPER")"

	case "$XDG_SESSION_TYPE" in
		wayland) swww img --transition-type any "$wallpaper_file" ;;
		x11)     feh --no-fehbg --bg-fill "$wallpaper_file" ;;
	esac

	notify-send --icon="$wallpaper_file" 'Wallpaper set'
}

trap 'change_wallpaper; kill "$PID"' USR1
trap 'kill "$PID"' HUP

case "$XDG_SESSION_TYPE" in
	wayland) printf 'Wayland Wallpaper Loop\n' ;;
	x11)     printf 'X11 Wallpaper Loop\n' ;;
esac

while true
do
	update_wallpaper
	sleep $SLEEPTIME &
	PID=$!
	wait $PID && change_wallpaper
done
