#!/bin/sh
swww_command="swww img --transition-type any"
feh_command="feh --no-fehbg --bg-fill"
wallpaper_loop_name="wallpaperLoop"

case "$XDG_SESSION_TYPE" in
	x11)
		cmd="$feh_command"
		break
		;;
	wayland)
		cmd="$swww_command"
		break
		;;
esac

[ -f "$1" ] && $cmd "$1" && exit 0

case "$1" in
	next)
		pgrep "$wallpaper_loop_name" | xargs ps --no-headers -o pid,command --ppid | awk '/sleep/ {print $1}' | xargs kill
		break
		;;
esac
