#!/bin/sh

WALLPAPER="/tmp/wallpaper.txt"
DAEMON="wallpaperLoop"
DAEMON_PID="$(pgrep "$DAEMON")"

if [ -f "$1" ]
then
	echo "$1" > "$WALLPAPER"
	kill -HUP "$DAEMON_PID"
	exit 0
fi

case "$1" in
	next) kill -USR1 "$DAEMON_PID" ;;
	reset-timer) kill -HUP "$DAEMON_PID" ;;
esac
