#!/bin/sh
# set -x

# Dependencies:
# - feh
# - swww
# - mpvpaper
# - ffmpegthumbnailer

usage() {
	echo "Usage: $(basename "$0") [directories]"
	echo
	echo "Options:"
	echo "  -h, --help                        Show usage page"
	echo "  --enable-videos                   Enable videos (wayland only)"
	echo "  --disable-videos                  Turn off video support"
	echo "  --mpv-options       <options>     Options to pass to mpv through mpvpaper"
	echo "  --sleep-interval                  Time interval in seconds between each" \
		"wallpaper"
	echo
	echo "Positional arguments:"
	echo "  directories               List of directories to search for wallpapers"
	echo
	echo "Examples:"
	echo "$(basename "$0")"
	echo "$(basename "$0") ~/Images/Wallpapers"
	echo "$(basename "$0") --disable-videos ~/Images/Wallpapers"
	echo "$(basename "$0") ~/Images/Wallpapers ~/Videos"
	echo "$(basename "$0") --mpv-options='--volume=5'"
	echo "$(basename "$0") --sleep-interval=10"
	exit 2
}

file_type() {
	local type="$(echo "$1" | grep --max-count=1 --only-matching '\.[a-zA-Z]\{3,4\}$')"

	case $type in
		\.mkv | \.avi | \.m4v | \.mp4 | \.webm) type=video ;;
		\.jpg | \.png | \.gif) type=image ;;
		*)
			debug-message 'ERROR' "Invalid filetype $type" >&2
			return
			;;
	esac

	echo "$type"
}

notify_wallpaper() {
	local wallpaper_file="$(head -1 "$WALLPAPER")"
	local type="$(file_type "$wallpaper_file")"
	local icon_file="$wallpaper_file"

	# TODO: video thumbnail for desktop notification icon
	if [ "$type" = video ]
	then
		icon_file=/tmp/wallpaper-thumbnail.png
		ffmpegthumbnailer -i "$wallpaper_file" -o "$icon_file" -s 0 -t "$(shuf --input-range=10-90 --head-count=1)%"
	fi
	notify-send \
		--icon="$icon_file" \
		--urgency=low \
		'Wallpaper Update' "$(basename "$wallpaper_file")"
}

change_wallpaper() {
	# shellcheck disable=2086
	if $ENABLE_VIDEOS
	then
		find $DIRS \
			-maxdepth 1 \
			-type f \
			-name "*.jpg" -o \
			-name "*.png" -o \
			-name "*.gif" -o \
			-name "*.mkv" -o \
			-name ".avi" -o \
			-name ".m4v" -o \
			-name ".mp4" -o \
			-name ".webm" \
			| shuf --head-count=1 > "$WALLPAPER"
	else
		find $DIRS \
			-maxdepth 1 \
			-type f \
			-name "*.jpg" -o \
			-name "*.png" -o \
			-name "*.gif" \
			| shuf --head-count=1 > "$WALLPAPER"
	fi

	debug-message 'OK' "Changed wallpaper to $(head -1 "$WALLPAPER")"
}

clear_screen() {
	case "$XDG_SESSION_TYPE" in
		wayland) swww clear ;;
	esac
}

update_wallpaper() {
	local wallpaper_file="$(head -1 "$WALLPAPER")"
	local type="$(file_type "$wallpaper_file")"

	if [ "$type" = video ] && ! $ENABLE_VIDEOS
	then
		debug-message 'ERROR' 'Videos are disabled'
		return
	elif [ "$type" = video ] && [ "$XDG_SESSION_TYPE" = x11 ]
	then
		debug-message 'ERROR' 'Videos are not supported by Xorg'
		return
	fi

	pause_sleep
	case "$XDG_SESSION_TYPE" in
		x11) feh --no-fehbg --bg-fill "$wallpaper_file" ;;
		wayland)
			case "$type" in
				video)
					clear_screen
					# TODO: Output to specific DISPLAY
					mpvpaper \
						--mpv-options="$mpv_options" \
						'*' "$wallpaper_file" &
					MPVPAPER_PID=$!
					;;
				image) swww img --transition-type any "$wallpaper_file" ;;
			esac
			;;

	esac

	debug-message 'OK' "Updated Wallpaper $wallpaper_file"
	notify_wallpaper


	if [ -n "$MPVPAPER_PID" ]
	then
		if wait "$MPVPAPER_PID"
		then
			MPVPAPER_PID=
			change_wallpaper
			kill_sleep
			return
		fi
	fi
	resume_sleep
}

kill_sleep() {
	if [ -z "$SLEEP_PID" ]
	then
		debug-message 'ERROR' 'No sleep pid'
		return
	fi

	kill "$SLEEP_PID"
	SLEEP_PID=
}

quit_mpvpaper() {
	if [ -z "$MPVPAPER_PID" ]
	then
		debug-message 'ERROR' 'No mpvpaper pid'
		return
	fi

	kill -TERM "$MPVPAPER_PID"
	MPVPAPER_PID=
}

pause_sleep() {
	if [ -z "$SLEEP_PID" ]
	then
		debug-message 'ERROR' 'No sleep pid'
		return
	fi

	kill -STOP "$SLEEP_PID"
}

resume_sleep() {
	if [ -z "$SLEEP_PID" ]
	then
		debug-message 'ERROR' 'No sleep pid'
		return
	fi
	
	kill -CONT "$SLEEP_PID"
}

_usr1_signal() {
	quit_mpvpaper
	change_wallpaper
	kill_sleep
}

_hup_signal() {
	quit_mpvpaper
	kill_sleep
}

SLEEP_TIME=600
SLEEP_PID=
WALLPAPER=/tmp/wallpaper.txt
MPVPAPER_PID=
case $XDG_SESSION_TYPE in
	wayland) ENABLE_VIDEOS=true ;;
	*)       ENABLE_VIDEOS=false ;;
esac
mpv_options='--really-quiet --sub-visibility=no --volume=24'

TEMP=$(getopt \
	--options 'h' \
	--long 'help,enable-videos,disable-videos,mpv-options:,sleep-interval:' \
	--name "$(basename "$0")" -- "$@")

if [ $? -ne 0 ]
then
	echo 'Terminating...' >&2
	exit 1
fi

# Note the quotes around "$TEMP": they are essential!
eval set -- "$TEMP"
unset TEMP

while true
do
	case "$1" in
		-h | --help)
			usage
			;;
		--enable-videos)
			ENABLE_VIDEOS=true
			[ "$XDG_SESSION_TYPE" = x11 ] && ENABLE_VIDEOS=false
			shift
			continue
			;;
		--disable-videos)
			ENABLE_VIDEOS=false
			shift
			continue
			;;
		--mpv-options)
			mpv_options="$2"
			shift 2
			continue
			;;
		--sleep-interval)
			SLEEP_TIME="$2"
			shift 2
			continue
			;;
		--)
			shift
			break
			;;
		*) # Option not dealt with
			echo "$1"
			echo 'Internal error!' >&2
			exit 1
			;;
	esac
done

[ "$#" = 0 ] \
	&& DIRS="$(xdg-user-dir PICTURES)/Wallpapers $(xdg-user-dir VIDEOS)" \
	|| DIRS="$@"

trap _usr1_signal USR1
trap _hup_signal HUP
# TODO: add signal to toggle ENABLE_VIDEOS

if [ "$(pgrep $(basename "$0") | wc --lines)" -gt 2 ]
then
	debug-message 'ERROR' "Another instance of $(basename "$0") running"
	exit 1
fi

debug-message 'INFO' "$(basename "$0") started"
debug-message 'INFO' "SLEEP_TIME    = $SLEEP_TIME"
debug-message 'INFO' "mpv-options   = $mpv_options"
debug-message 'INFO' "ENABLE_VIDEOS = $ENABLE_VIDEOS"
debug-message 'INFO' "DIRS          = $DIRS"

if [ "$XDG_SESSION_TYPE" = wayland ]
then
	swww init
fi

change_wallpaper

while true
do
	sleep "$SLEEP_TIME" &
	SLEEP_PID=$!

	update_wallpaper

	if wait "$SLEEP_PID"
	then
		change_wallpaper
	fi
done
